In [1]:
import os
import pandas as pd
import datetime as dt
from urllib.parse import urlparse
import re
import numpy as np

### Part 1: Combine multiple tables into a single table

In [2]:
path = "D:/Data Self Learning/Tran Hoang Long _ Data Analyst Course/Data Analyst/Market basket Association/Raw Data/"
frames = []
for file in os.listdir(path):
    if file.endswith(".xlsx"):
        filepath = os.path.join(path, file)
        df_tmp = pd.read_excel(filepath)
        frames.append(df_tmp)
df = pd.concat(frames, ignore_index=True)

In [3]:
df.head(10)

,Nhà sản xuất,Khách hàng,Email khách hàng,Năm,Tháng,Ngày,Nguồn lưu lượng (Traffic),Tham số,Nguồn giới thiệu (Referral),UTM_campaign,...,T.trạng đ.hàng,Phương thức thanh toán,Số đơn hàng,Doanh thu,Tiền khuyến mãi,Doanh thu thuần,Tổng hóa đơn,Đã thu,Số lượng,Vận chuyển
0,--,Hoàng khánh ngọc,khanhngoc20077@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,0,0.0,0.0,30000.0,0.0,0,30000
1,Maybelline New York,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,Direct,--,--,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,199000,0.0,199000.0,199000.0,0.0,1,0
2,--,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,Direct,--,--,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,0,0.0,0.0,30000.0,0.0,0,30000
3,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,210005,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,1,-1.0,0.0,0.0,0.0,1,0
4,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,210005,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,2,-2.0,0.0,0.0,0.0,2,0
5,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,199000,-20000.0,179000.0,179000.0,0.0,1,0
6,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,1,0.0,1.0,1.0,0.0,1,0
7,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,109000,0.0,109000.0,109000.0,0.0,1,0
8,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,169000,0.0,169000.0,169000.0,0.0,1,0
9,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,169000,0.0,169000.0,169000.0,0.0,1,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28449 entries, 0 to 28448
Data columns (total 36 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Nhà sản xuất                 28449 non-null  object
 1   Khách hàng                   28449 non-null  object
 2   Email khách hàng             28449 non-null  object
 3   Năm                          28449 non-null  datetime64[ns]
 4   Tháng                        28449 non-null  datetime64[ns]
 5   Ngày                         28449 non-null  datetime64[ns]
 6   Nguồn lưu lượng (Traffic)    28449 non-null  object
 7   Tham số                      28206 non-null  object
 8   Nguồn giới thiệu (Referral)  28449 non-null  object
 9   UTM_campaign                 28449 non-null  object
 10  UTM_content                  28449 non-null  object
 11  UTM_medium                   28449 non-null  object
 12  UTM_source                   28449 non-null  object
 13  UTM_term                     28449 non-null  object
 14  Chi nhánh                    28449 non-null  object
 15  Nhân viên tạo                28449 non-null  object
 16  Loại sản phẩm                28449 non-null  object
 17  Tỉnh thành                   28449 non-null  object
 18  Trang                        28449 non-null  object
 19  Kênh bán hàng                28449 non-null  object
 20  Đơn hàng                     28449 non-null  int64
 21  Sản phẩm                     28449 non-null  object
 22  SKU                          28449 non-null  object
 23  Quận huyện vận chuyển        28449 non-null  object
 24  Phiên bản                    28449 non-null  object
 25  T.trạng t.toán               28449 non-null  object
 26  T.trạng đ.hàng               28449 non-null  object
 27  Phương thức thanh toán       28449 non-null  object
 28  Số đơn hàng                  28449 non-null  int64
 29  Doanh thu                    28449 non-null  int64
 30  Tiền khuyến mãi              28449 non-null  float64
 31  Doanh thu thuần              28449 non-null  float64
 32  Tổng hóa đơn                 28449 non-null  float64
 33  Đã thu                       28449 non-null  float64
 34  Số lượng                     28449 non-null  int64
 35  Vận chuyển                   28449 non-null  int64
dtypes: datetime64[ns](3), float64(4), int64(5), object(24)
memory usage: 7.8+ MB

##### 1. Change table column name from vietnamese to english

In [5]:
rename_columns = {
    "Nhà sản xuất": "manufacturer",
    "Khách hàng": "customer",
    "Email khách hàng": "customer_email",
    "Năm": "year",
    "Tháng": "month",
    "Ngày": "date",
    "Nguồn lưu lượng (Traffic)": "traffic_source",
    "Tham số": "parameter",
    "Nguồn giới thiệu (Referral)": "referral",
    "UTM_campaign": "utm_campaign",
    "UTM_content": "utm_content",
    "UTM_medium": "utm_medium",
    "UTM_source": "utm_source",
    "UTM_term": "utm_term",
    "Chi nhánh": "branch",
    "Nhân viên tạo": "created_by",
    "Loại sản phẩm": "product_category",
    "Tỉnh thành": "province",
    "Trang": "page",
    "Kênh bán hàng": "sale_channel",
    "Đơn hàng": "order_id",
    "Sản phẩm": "product_name",
    "SKU": "sku",
    "Quận huyện vận chuyển": "district",
    "Phiên bản": "version",
    "T.trạng t.toán": "payment_status",
    "T.trạng đ.hàng": "order_status",
    "Phương thức thanh toán": "payment_method",
    "Số đơn hàng": "order_count",
    "Doanh thu": "revenue",
    "Tiền khuyến mãi": "discount_amount",
    "Doanh thu thuần": "net_revenue",
    "Tổng hóa đơn": "total_invoice",
    "Đã thu": "amount_received",
    "Số lượng": "quantity",
    "Vận chuyển": "shipping_fee"
}

df.rename(columns=rename_columns, inplace=True)

In [6]:
df.head(10)

,manufacturer,customer,customer_email,year,month,date,traffic_source,parameter,referral,utm_campaign,...,order_status,payment_method,order_count,revenue,discount_amount,net_revenue,total_invoice,amount_received,quantity,shipping_fee
0,--,Hoàng khánh ngọc,khanhngoc20077@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,0,0.0,0.0,30000.0,0.0,0,30000
1,Maybelline New York,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,Direct,--,--,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,199000,0.0,199000.0,199000.0,0.0,1,0
2,--,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,Direct,--,--,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,0,0.0,0.0,30000.0,0.0,0,30000
3,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,210005,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,1,-1.0,0.0,0.0,0.0,1,0
4,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,210005,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,2,-2.0,0.0,0.0,0.0,2,0
5,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,199000,-20000.0,179000.0,179000.0,0.0,1,0
6,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,1,0.0,1.0,1.0,0.0,1,0
7,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,109000,0.0,109000.0,109000.0,0.0,1,0
8,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,169000,0.0,169000.0,169000.0,0.0,1,0
9,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,169000,0.0,169000.0,169000.0,0.0,1,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28449 entries, 0 to 28448
Data columns (total 36 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   manufacturer      28449 non-null  object
 1   customer          28449 non-null  object
 2   customer_email    28449 non-null  object
 3   year              28449 non-null  datetime64[ns]
 4   month             28449 non-null  datetime64[ns]
 5   date              28449 non-null  datetime64[ns]
 6   traffic_source    28449 non-null  object
 7   parameter         28206 non-null  object
 8   referral          28449 non-null  object
 9   utm_campaign      28449 non-null  object
 10  utm_content       28449 non-null  object
 11  utm_medium        28449 non-null  object
 12  utm_source        28449 non-null  object
 13  utm_term          28449 non-null  object
 14  branch            28449 non-null  object
 15  created_by        28449 non-null  object
 16  product_category  28449 non-null  object
 17  province          28449 non-null  object
 18  page              28449 non-null  object
 19  sale_channel      28449 non-null  object
 20  order_id          28449 non-null  int64
 21  product_name      28449 non-null  object
 22  sku               28449 non-null  object
 23  district          28449 non-null  object
 24  version           28449 non-null  object
 25  payment_status    28449 non-null  object
 26  order_status      28449 non-null  object
 27  payment_method    28449 non-null  object
 28  order_count       28449 non-null  int64
 29  revenue           28449 non-null  int64
 30  discount_amount   28449 non-null  float64
 31  net_revenue       28449 non-null  float64
 32  total_invoice     28449 non-null  float64
 33  amount_received   28449 non-null  float64
 34  quantity          28449 non-null  int64
 35  shipping_fee      28449 non-null  int64
dtypes: datetime64[ns](3), float64(4), int64(5), object(24)
memory usage: 7.8+ MB

##### 2. Drop some unnecessary columns for transaction data

In [8]:
# các cột year, month ở dạng datetime chỉ chứa dữ liệu về năm, tháng nên trở nên dư thừa
# các cột như parameter, utm_campaign, utm_content, utm_medium, utm_source, utm_term, created_by, page, sale_chanel, sku không có đầy dủ thông tin hoặc không có tác dụng cho mục đích xây báo cáo sau này
# cột payment_status không có tác dụng bởi vì đây là dữ liệu từ năm 2021

df.drop(['year', 'month', 'parameter', 'utm_campaign', 'utm_content', 'utm_medium', 'utm_source', 'utm_term', 'created_by', 'page', 'sale_channel', 'sku', 'payment_status', 'order_count', 'net_revenue'], axis= 1, inplace= True)

### Part 2: Data Cleaning

In [9]:
# Dữ liệu nguồn chứa các bản ghi về shipping, quà tặng, giao dịch của từng món hàng trong hoá đơn
# Cần tách ra để dễ xử lý dữ liệu và phù hợp cho việc Data Modeling sau này

shipping_df = df[df['product_name'] == '--'][['order_id', 'shipping_fee']]

df_gift = df[
    df['product_name'].str.contains(r'\[(quà tặng|gift|Quà tặng không bán)\]', case=False, na=False)
][['order_id', 'product_name']]

# Xoá cả dòng shipping và dòng quà tặng
df = df[
    (df['product_name'] != '--') & 
    (~df['product_name'].str.contains(r'\[(quà tặng|gift|Quà tặng không bán)\]', case=False, na=False))
]

# Xoá các ký tự không cần thiết trong tên quà tặng
df_gift = df_gift.rename(columns={'product_name': 'gift_name'})

df_gift['gift_name'] = df_gift['gift_name'].str.replace(
    r'\[(quà tặng|gift|Quà tặng không bán)\]', 
    '', 
    case=False,  # không phân biệt hoa thường
    regex=True
).str.strip()

# Chỉnh sửa kiểu dữ liệu cho cột date
df['date'] = df['date'].dt.date

C:\Users\MSI\AppData\Local\Temp\ipykernel_2208\2725251162.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df['product_name'].str.contains(r'\[(quà tặng|gift|Quà tặng không bán)\]', case=False, na=False)
C:\Users\MSI\AppData\Local\Temp\ipykernel_2208\2725251162.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  (~df['product_name'].str.contains(r'\[(quà tặng|gift|Quà tặng không bán)\]', case=False, na=False))

In [10]:
# Một số dữ liệu ở cột referral quá dài không phù hợp để dưa vào mysql
# Cần chuẩn hoá lại dữ liệu của cột mà vẫn giữ nguyên khả năng đưa ra insight

def extract_base_url(url):
    try:
        parsed = urlparse(str(url))
        return f"{parsed.scheme}://{parsed.netloc}/" if parsed.netloc else None
    except:
        return None

df['clean_referral'] = df['referral'].apply(extract_base_url)

In [11]:
df[['referral', 'clean_referral']].drop_duplicates().head(10)

,referral,clean_referral
1,--,None
3,http://m.facebook.com,http://m.facebook.com/
5,https://shop.lorealparis.com.vn//?ref=210007&u...,https://shop.lorealparis.com.vn/
10,https://www.google.com/,https://www.google.com/
24,https://www.youtube.com/,https://www.youtube.com/
33,https://l.facebook.com/,https://l.facebook.com/
68,http://m.facebook.com/,http://m.facebook.com/
273,https://m.kenh14.vn/5-kem-chong-nang-hack-da-d...,https://m.kenh14.vn/
414,https://shop.maybelline.vn/collections/son-kem...,https://shop.maybelline.vn/
578,https://shop.maybelline.vn//?ref=210007&utm_so...,https://shop.maybelline.vn/

In [12]:
df['referral'] = df['clean_referral']
df.drop(['clean_referral'], axis=1, inplace=True)

In [13]:
df['referral'].value_counts()

referral
http://m.facebook.com/                   2524
https://shop.lorealparis.com.vn/         1921
https://www.goshopback.vn/               1879
https://l.facebook.com/                  1244
https://click.accesstrade.vn/            1051
https://shop.maybelline.vn/               655
https://www.google.com/                   638
https://www.lorealparis.com.vn/           482
https://l.instagram.com/                  293
https://instabio.cc/                       94
https://www.instagram.com/                 70
https://www.youtube.com/                   66
android-app://org.telegram.messenger/      40
https://m.facebook.com/                    33
http://linksanpham.clix9.com/              30
https://www.google.com.vn/                 29
https://fanlnk.to/                         18
https://pub.accesstrade.vn/                16
https://vinid.net/                         16
https://m.kenh14.vn/                       14
android-app://com.google.android.gm/       10
https://www.maybelline.vn/                  8
android-app://m.facebook.com/               8
https://lm.facebook.com/                    6
https://app.harasocial.com/                 4
https://l.messenger.com/                    3
https://kenh14.vn/                          3
https://pub2.accesstrade.vn/                2
https://coccoc.com/                         2
http://app.kenh14.vn/                       1
https://www.ecosia.org/                     1
Name: count, dtype: int64

In [14]:
# Trích xuất tên kênh từ các url ở trên

# Danh sách từ khóa & kênh tương ứng
channel_map = {
    'facebook': 'facebook',
    'instagram': 'instagram',
    'youtube': 'youtube',
    'google': 'google',
    'kenh14': 'kenh14',
    'maybelline': 'maybelline',
    'lorealparis': 'lorealparis',
    'harasocial': 'harasocial',
    'accesstrade': 'accesstrade',
    'shopback': 'goshopback',
    'coccoc': 'coccoc',
    'telegram': 'telegram',
    'messenger': 'messenger',
    'vinid': 'vinid',
    'fanlnk': 'fanlnk',        # URL thực tế là fanlnk.to (không phải fanlink.to)
    'instabio': 'instabio',
    'linksanpham': 'linksanpham',
    'ecosia': 'ecosia'
}

def match_channel(url):
    if pd.isna(url):
        return 'none'
    url = str(url).lower()
    for keyword, channel in channel_map.items():
        if keyword in url:
            return channel
    return 'other'


df['Channel'] = df['referral'].apply(match_channel)

In [15]:
df['Channel'].value_counts()

Channel
none           11899
facebook        3815
lorealparis     2403
goshopback      1879
accesstrade     1069
google           677
maybelline       663
instagram        363
instabio          94
youtube           66
telegram          40
linksanpham       30
kenh14            18
fanlnk            18
vinid             16
harasocial         4
messenger          3
coccoc             2
ecosia             1
Name: count, dtype: int64

In [16]:
df['traffic_source'].value_counts()

traffic_source
Direct           11865
Referral          6206
fb                4641
Social             346
Search Engine        2
Name: count, dtype: int64

In [17]:
# Xử lý các cột liên quan đến traffice và url để phù hợp với việc phân tích

channel_to_source = {
    "none": "Direct",
    "facebook": "Facebook",
    "lorealparis": "Affiliate",
    "goshopback": "Affiliate",
    "accesstrade": "Affiliate",
    "google": "Search Engine",
    "maybelline": "Affiliate",
    "instagram": "Social",
    "instabio": "Social",
    "youtube": "Social",
    "telegram": "Social",
    "linksanpham": "Affiliate",
    "kenh14": "Affiliate",
    "other": "Affiliate",
    "vinid": "Affiliate",
    "harasocial": "Affiliate",
    "messenger": "Social",
    "coccoc": "Search Engine",
    "ecosia": "Search Engine",
    "fanlnk": "Affiliate"      # fanlnk.to là affiliate link
}

traffic_source_mapping = {
    "Direct": "Direct",
    "fb": "Facebook",
    "Referral": "Affiliate",
    "Social": "Social",
    "Search Engine": "Search Engine"
}

# Hàm xử lý logic chuyển đổi
def determine_final_source(row):
    ts = row['traffic_source']
    ch = row['Channel']
    
    if ts in traffic_source_mapping:
        return traffic_source_mapping[ts]
    elif ch in channel_to_source:
        return channel_to_source[ch]
    else:
        return "Affiliate"

# Tạo cột mới
df['traffic_source'] = df.apply(determine_final_source, axis=1)
df['traffic_source'].value_counts()
# Xoá cột referral và traffic_source cũ
df.drop(['referral', 'Channel'], axis= 1, inplace= True)

In [18]:
# Ở cột customer_email, một số bản ghi có chứa email test từ hệ thống. VD: test@test.com
# Dùng regex chính xác hơn để tránh filter nhầm email hợp lệ như attest@gmail.com

df = df[~df['customer_email'].str.contains(r'(^test|@test\.)', regex=True, case=False, na=False)]

C:\Users\MSI\AppData\Local\Temp\ipykernel_2208\4079209220.py:4: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df = df[~df['customer_email'].str.contains(r'(^test|@test\.)', regex=True, case=False, na=False)]

In [19]:
df.head(10)

,manufacturer,customer,customer_email,date,traffic_source,branch,product_category,province,order_id,product_name,district,version,order_status,payment_method,revenue,discount_amount,total_invoice,amount_received,quantity,shipping_fee
1,Maybelline New York,982285478,thuyan91096@gmail.com,2021-05-26,Direct,Kho Miền Bắc - MBL,Face,Cần Thơ,112403,Kem Nền Siêu Che Phủ Lâu Trôi Maybelline Super...,Quận Ninh Kiều,112 Natural Ivory,Không hủy,Thanh toán khi giao hàng (COD),199000,0.0,199000.0,0.0,1,0
3,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-05-26,Facebook,Kho Miền Nam - OAP,Khác,Hồ Chí Minh,112402,Kem chống nắng L'Oreal Paris UV Perfect trắng ...,Quận 1,Default Title,Không hủy,Thanh toán khi giao hàng (COD),1,-1.0,0.0,0.0,1,0
4,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-05-26,Facebook,Kho Miền Nam - OAP,Khác,Hồ Chí Minh,112402,Kem dưỡng L’Oreal Paris White Perfect ban ngày...,Quận 1,7ml,Không hủy,Thanh toán khi giao hàng (COD),2,-2.0,0.0,0.0,2,0
5,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-05-26,Facebook,Kho Miền Bắc - OAP,Khác,Thanh Hóa,112400,Kem chống nắng Nâng tông Giảm thâm Mịn Nhẹ Bảo...,Huyện Vĩnh Lộc,Kiềm dầu thoáng mịn (Viền Xanh lá),Không hủy,Thanh toán khi giao hàng (COD),199000,-20000.0,179000.0,0.0,1,0
6,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-05-26,Facebook,Kho Miền Bắc - OAP,Khác,Lai Châu,112399,Serum siêu cấp ẩm sáng da 7.5ml,Huyện Phong Thổ,Default Title,Không hủy,Thanh toán khi giao hàng (COD),1,0.0,1.0,0.0,1,0
7,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-05-26,Facebook,Kho Miền Bắc - OAP,Khác,Lai Châu,112399,Nước hoa hồng se khít lỗ chân lông và trắng mị...,Huyện Phong Thổ,200ml,Không hủy,Thanh toán khi giao hàng (COD),109000,0.0,109000.0,0.0,1,0
8,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-05-26,Facebook,Kho Miền Bắc - OAP,Dưỡng Chất,Lai Châu,112399,Kem dưỡng trắng sáng đều màu da L'Oreal White ...,Huyện Phong Thổ,50ml,Không hủy,Thanh toán khi giao hàng (COD),169000,0.0,169000.0,0.0,1,0
9,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-05-26,Facebook,Kho Miền Bắc - OAP,Dưỡng Chất,Lai Châu,112399,Kem dưỡng da trắng sáng L'Oreal White Perfect ...,Huyện Phong Thổ,50ml,Không hủy,Thanh toán khi giao hàng (COD),169000,0.0,169000.0,0.0,1,0
10,L'Oréal Paris,THÚY DIỄM TRẦN THỦY,hung.huynh@loreal.com,2021-05-26,Affiliate,Kho Miền Nam - OAP,Khác,Tây Ninh,112398,Kem chống nắng L'Oreal Paris UV Perfect trắng ...,Huyện Bến Cầu,Default Title,Không hủy,Thanh toán khi giao hàng (COD),4,0.0,4.0,0.0,4,0
11,L'Oréal Paris,THÚY DIỄM TRẦN THỦY,hung.huynh@loreal.com,2021-05-26,Affiliate,Kho Miền Nam - OAP,Sữa Rửa Mặt,Tây Ninh,112398,Sữa rửa mặt dưỡng trắng và sáng mịn da L'Oréal...,Huyện Bến Cầu,Default Title,Không hủy,Thanh toán khi giao hàng (COD),84000,0.0,84000.0,0.0,1,0

In [20]:
df['product_name'].unique()

array(['Kem Nền Siêu Che Phủ Lâu Trôi Maybelline Super Stay Full Coverage Foundation 30ml',
       "Kem chống nắng L'Oreal Paris UV Perfect trắng sáng tức thì 15ml",
       'Kem dưỡng L’Oreal Paris White Perfect ban ngày SPF17 PA++ 7ml',
       'Kem chống nắng Nâng tông Giảm thâm Mịn Nhẹ Bảo vệ da L’Oreal Paris UV Defender 50ml\u200b',
       'Serum siêu cấp ẩm sáng da 7.5ml',
       "Nước hoa hồng se khít lỗ chân lông và trắng mịn da L'Oréal Paris White Perfect 200ml",
       "Kem dưỡng trắng sáng đều màu da L'Oreal White Perfect Fairness Revealing Soothing Night Cream 50ml",
       "Kem dưỡng da trắng sáng L'Oreal White Perfect Day Cream SPF17 PA++ 50ml",
       "Sữa rửa mặt dưỡng trắng và sáng mịn da L'Oréal Paris White Perfect 100ml",
       "Serum Siêu cấp ẩm sáng da L'Oreal Paris Pure Hyaluronic Acid 1.5% 30ml",
       "Kem dưỡng săn chắc da và giảm nếp nhăn ban đêm L'Oréal Paris Revitalift 50ml",
       "Nước tẩy trang đa năng làm sạch sâu 3-in-1 L'Oréal Paris Micellar Water 400ml - Dưỡng ẩm da",
       'Bút Cushion Che Khuyết Điểm Đa Năng Instant Age Rewind Eraser Multi-use Concealer Maybelline New York 6ml',
       'Son Lì Mịn Môi Maybelline New York',
       'Phấn Nền Kiềm Dầu Chống Nắng Tiệp Mọi Tông Da SPF 32 PA+++ Fit Me Skin-Fit Powder Foundation Maybelline New York 9g',
       'Chì Kẻ Mày 2 Đầu Sắc Nét Tự Nhiên Maybelline New York Define & Blend Brow Pencil 0.16g',
       'TÚI LƯỚI DU LỊCH TIỆN DỤNG_MÀU TRẮNG',
       "Sữa tẩy trang L'Oreal Paris Dermo Expertise Gentle Cleansing Milk 200ml",
       "Nước tẩy trang đa năng làm sạch sâu 3-in-1 L'Oréal Paris Micellar Water 400ml - Làm mát da",
       'Son Kem Lì 16h Lâu Trôi Maybelline New York Super Stay Matte Ink Lipstick 5ml',
       "Sữa rửa mặt dưỡng trắng và sáng mịn da L'Oréal Paris White Perfect 50ml",
       "Phấn nền mịn da L'Oreal Paris True Match 8g",
       "Kem nền mịn da dạng lỏng L'Oréal Paris True Match Liquid Foundation 30ml",
       "Nước tẩy trang L'Oreal Paris 3-in-1 Micellar Water 400ml: Làm Sạch Trang Điểm",
       "Kem dưỡng trắng mịn và giảm thâm nám ban đêm L'Oreal Paris White Perfect Clinical Night Cream 50ml",
       "Nước hoa hồng se khít lỗ chân lông và săn chắc da L'oreal Paris Revitalift 200ml",
       "Tinh chất tăng cường dưỡng da trắng mịn & giảm thâm nám L'Oréal Paris White Perfect Clinical 30ml",
       'Nước Tẩy Trang Micellar Dưỡng Da Không Cồn 4 Trong 1 Maybelline New York Micellar Water 4-in-1',
       "Bút Kẻ Mày 3 Đầu L'Oréal Paris Brow Artist Designer Pro 3-IN-1",
       "Kem dưỡng trắng mịn và giảm thâm nám ban ngày L'Oréal Paris White Perfect Clinical SPF19/PA+++ 50ml",
       "Chì Kẻ Mày 2 Đầu L'Oréal Paris Brow Artist Xpert",
       'Tẩy Trang Mắt Môi Chuyên Dụng Maybelline New York Eye & Lip Makeup Remover',
       'Phấn Phủ Mịn Nhẹ Kiềm Dầu Fit Me Matte Poreless Powder Maybelline New York 8.5g',
       'Kem Nền Mịn Nhẹ Kiềm Dầu Fit Me Maybelline New York Matte Poreless Foundation 30ml',
       "Dưỡng Chất Căng Mướt Da L'Oréal Paris Revitalift Crystal Micro Essence 130ml",
       "Son tint mịn lì cao cấp L'Oréal Paris Rouge Signature 7ml",
       "Kem chống nắng bảo vệ & dưỡng da se mịn lỗ chân lông & chống ô nhiễm L'Oreal Paris UV Perfect fresh & Matte SPF50/PA++++ 7ml",
       "Nước Tẩy Trang Tươi Mát L'Oreal Paris 3-in-1 Micellar Water Sạch Sâu 95ml",
       'Son Kem Lì Nhẹ Môi Maybelline New York Sensational Liquid Matte Lipstick 7ml',
       "Kem chống nắng dưỡng trắng da L'Oréal Paris UV Perfect Rosy White SPF50+/PA ++++",
       "Sữa rửa mặt săn chắc da L'Oreal Revitalift Milky Cleansing Foam 100ml",
       "Kem dưỡng săn chắc da và giảm nếp nhăn ban ngày L'Oréal Paris Revitalift SPF23 PA++ 50ml",
       "Kem nền mịn nhẹ lâu trôi L'Oréal Paris Infallible Fresh Wear 24h 30ml",
       'Mascara Dài Mi Và Cong Mi Maybelline New York Hyper Curl Waterproof Chuốt Mi Đen Không Lem Không Trôi 9.2ml',
       "Mặt nạ kết hợp serum căng mịn L'Oreal Paris Revitalift Fresh Mix Plumping Serum",
       'Son Kem Lì Nhẹ Môi Phiên Bản Tông Đất Maybelline New York Sensational Liquid Matte The Nudes Lipstick 7ml',
       "Hoạt chất tươi trẻ da chống lão hóa L'Oreal Paris Youth Code Skin Activating Ferment Pre-Essence 30ml",
       "Nước Tẩy Trang Tươi Mát L'Oreal Paris 3-in-1 Micellar Water dưỡng ẩm da 95ml",
       'Phấn Nền Kiềm Dầu Chống Nắng 12H SPF28 PA+++ Mịn Lì Lâu Trôi Fit Me Maybelline New York Compact Powder 6g',
       'Kem Nền Mịn Nhẹ Kiềm Dầu Chống Nắng Fit Me Dạng Tuýp Maybelline New York Matte Foundation 5ml - Màu 120',
       'Son Bút Chì Mịn Lì 8h Lâu Trôi Maybelline New York Super Stay Ink Crayon Lipstick 1.2g',
       "Mặt nạ giấy dưỡng chất cô đặc L'Oréal Paris Revitalift Pro-Youth Face Mask - Dưỡng Trắng Da",
       "Dưỡng Chất Căng Mướt Da L'Oréal Paris Revitalift Crystal Micro Essence 65ml",
       "Son Thỏi  lì Mịn Môi L'Oréal Paris Color Riche Matte 3.7g",
       "Túi tote L'Oréal Paris I'M WORTH IT",
       "Dầu dưỡng chiết xuất tinh dầu hoa tự nhiên L'Oréal Paris Elseve Extraordinary Oil 100ml",
       "Túi metallic Da Pha Lê L'Oreal Paris",
       "Màu nhuộm dưỡng tóc phủ bạc L'Oreal Paris Excellence Crème 172ml",
       'Son Dưỡng Môi Baby Lips Bloom Maybelline New York Chống Nắng SPF 16 (Có Màu) 1.7g',
       "Kem chống nắng dưỡng ẩm & chống nhờn rít L'Oréal Paris UV Perfect Super Aqua Essence SPF50+ PA++++",
       'Bút Kẻ Mắt Nước Siêu Mảnh Không Lem Không Trôi Maybelline New York Hypersharp Liner Đen 0.5g',
       "Kem chống nắng trang điểm L'Oréal Paris UV Perfect BB Max SPF50+ PA++++",
       'Kem lót mịn da che khuyết điểm Maybelline New York Baby Skin Pore Eraser Primer 22ml',
       "Mặt nạ dưỡng chất pha lê Revitalift Crystal Micro-Essence Treatment Mask L'Oreal Paris 25g",
       "Nước Tẩy Trang Tươi Mát L'Oreal Paris 3-in-1 Micellar Water (95ml) tươi mát da",
       "Kem ủ phục hồi tóc L'Oréal Paris Total Repair 5 200ml",
       "Dầu gội phục hồi tóc L'oreal Paris Elseve Total Repair 5 Repairing Shampoo 650ml",
       "Kem ủ ngăn gãy rụng tóc L'Oreal Paris Elseve Fall Resist 3X 200ml",
       "Dầu xả Phục Hồi Tóc L'oreal Paris Elseve Total Repair 5 Repairing Conditioner 325ml",
       "Dầu gội phục hồi tóc L'oreal Paris Elseve Total Repair 5 Repairing Shampoo 330ml",
       "Kem chống nắng kiềm dầu & se mịn lỗ chân lông L'Oréal Paris UV Perfect Fresh & Matte SPF50+ PA++++",
       'Phấn Má Hồng Mịn Nhẹ Tự Nhiên Giữ Màu Chuẩn Fit Me Blush Maybelline New York 4.5g',
       "Son satin mịn mượt cao cấp L'Oreal Paris Color Riche Satin 3.7g",
       'Kẻ Mắt Nước Maybelline Sắc Nét Không Trôi Màu Đen HyperSharp Power Black Liquid Liner 0.5g',
       "Kem dưỡng da vùng mắt chống lão hóa L'Oreal Paris Dex Revitalift Eye Cream 15ml",
       'Mascara Dài Mi & Tơi Mi Tự Nhiên Maybelline New York Lash Sensational Waterproof Chuốt Mi Không Lem Không Trôi 10ml',
       'Mascara Uốn Mi, Nâng Mi Và Làm Dày Mi Maybelline New York Falsies Lash Lift 8.6ml',
       'Bảng Phấn Mắt Maybelline New York 6 Màu Mini Palette 4g',
       'Kem Nền Mịn Nhẹ Kiềm Dầu Fit Me Dạng Tuýp Maybelline New York Matte Foundation 18ml',
       'Kem Che Khuyết Điểm Mịn Lì Tiệp Mọi Tông Da Fit Me Concealer Maybelline New York 6.8ml',
       'Mascara Dày Mi Cực Đại Maybelline New York The Magnum Big Shot Waterproof Chuốt Mi Không Lem Không Trôi 10ml',
       "Dầu gội chiết xuất tinh dầu hoa tự nhiên L'Oreal Paris Elseve Extraordinary Oil 130ml",
       "Dưỡng Chất Căng Mướt Da L'Oreal Paris Crystal Micro Essence 22ml",
       'Mascara Dưỡng Mi Collagen Dày Mi Gấp 10 Lần Maybelline New York Colossal Waterproof Chuốt Mi Không Lem Không Trôi 9.2ml',
       "Kem ủ chiết xuất tinh dầu hoa tự nhiên L'Oréal Paris Elseve Extraordinary Oil 200ml",
       "Dầu gội ngăn gãy rụng tóc L'Oreal Paris Elseve Fall Resist 3X Shampoo 650ml",
       "Mascara L'Oreal Làm Cong Và Dày Mi Curl Impact Collagene 11ml",
       "Dầu xả ngăn gãy rụng tóc L'Oreal Paris Elseve Fall Resist 3X Conditioner 325ml",
       'Bút Kẻ Mắt Nước Lâu Trôi 36H không thấm nước Maybelline New York Line Tattoo High Impact Liner 1g',
       "Dầu gội chiết xuất tinh dầu hoa tự nhiên L'Oréal Paris Elseve Extraordinary Oil 650ml",
       'Bộ thuốc nhuộm dưỡng tóc phủ bạc Excellence No.6.35 - Nâu chocolate',
       "Dầu xả chiết xuất tinh dầu hoa tự nhiên L'Oréal Paris Elseve Extraordinary Oil 325ml",
       "Dầu gội chiết xuất tinh dầu hoa tự nhiên L'Oréal Paris Elseve Extraordinary Oil 330ml",
       "Dầu gội ngăn gãy rụng tóc L'Oreal Paris Elseve Fall Resist 3X Shampoo 330ml",
       "Dầu gội ngăn gãy rụng tóc L'Oreal Paris Elseve Fall Resist 3X Shampoo 170ml",
       "Kem Nhuộm Dưỡng Tóc Phủ Bạc L'Oréal Paris Excellence Crème 172ml - 1 Đen Tự Nhiên",
       "Kem nhuộm dưỡng tóc phủ bạc L'Oréal Paris Excellence Crème 172ml - Nâu tự nhiên",
       "Màu nhuộm dưỡng tóc phủ bạc L'Oreal Paris Excellence Crème 172ml Nâu Hạt Dẻ",
       "Kem che khuyết điểm L'Oreal Paris True Match The One Concealer 6.8ml",
       "Mặt nạ giấy dưỡng chất cô đặc L'Oréal Paris Revitalift Pro-Youth Face Mask - Săn Chắc Da",
       "Mặt Nạ Giấy Dưỡng Chất Cô Đặc L'Oréal Paris Revitalift Pro-Youth Face Mask – Dưỡng ẩm da",
       "Bút Kẻ Mắt Lâu Trôi L'Oreal Paris Flash Cat Eye By Superliner",
       'Chì Kẻ Mày 2 Đầu Với Đầu Chì Xéo Mềm Mịn 12H Maybelline New York Fashion Brow Cream Pencil 0.8g',
       "Dầu xả L'Oréal Paris Elseve Color Protect 7 Weeks Conditioner 325ml",
       "Dầu gội giữ màu tóc nhuộm L'oreal Paris Elseve Color Protect Protecting Shampoo",
       "Kem Che Khuyết Điểm L'Oreal Paris Infallible More Than Concealer",
       'Phấn Phủ Kiềm Dầu Siêu Mịn 24h Chống Nắng SPF 32 PA+++ Clear Smooth All In One Maybelline New York Powder Foundation 9g',
       'Kem nền lâu trôi L’Oreal Paris Infallible 24H MATTE COVER',
       'Phấn Phủ Mịn Da Chống Nhờn Maybelline Clear Smooth All In One Powder 9g',
       "Dưỡng chất căng mướt da L'Oreal Paris Crystal Micro Essence 130ml - Phiên bản giới hạn",
       "Kem nhuộm dưỡng tóc phủ bạc L'Oréal Paris Excellence Crème 172ml - Nâu đen tự nhiên",
       'Kem Trang Điểm Bb Che Khuyết Điểm Và Chống Nắng Maybelline New York Super Bb Ultra Cover SPF 50 PA++++ 30ml',
       "Màu nhuộm dưỡng tóc phủ bạc L'Oreal Paris Excellence Crème 172ml Vàng Sáng",
       "Nước tẩy trang mắt và môi L'Oreal Paris Gentle Care 125ml",
       "Mascara làm dày và dài mi L'Oréal Paris Lash Paradise 7.6ml",
       "Bộ Serum Siêu Cấp Ẩm Và Sáng Da L'ORÉAL PARIS Pure Hyaluronic Acid 1.5%",
       "Kem nhuộm dưỡng tóc phủ bạc L'Oréal Paris Excellence Crème 172ml - Nâu ánh tím",
       'Bút kẻ mắt 2 đầu Super Liner Duo Designer',
       "Màu nhuộm dưỡng tóc phủ bạc L'Oreal Paris Excellence Crème 172ml Nâu chocolate",
       "Dầu xả ngăn gãy rụng tóc L'Oreal Paris Elseve Fall Resist 3X Conditioner 165ml",
       "Kem nhuộm dưỡng tóc phủ bạc L'Oréal Paris Excellence Crème 172ml - Nâu đồng ánh đỏ",
       'Bộ Thuốc Nhuộm Dưỡng Tóc Phủ Bạc Excellence No.3 - Nâu Đen Tự Nhiên',
       "Kem nhuộm dưỡng tóc phủ bạc L'Oréal Paris Excellence Crème 172ml - Nâu ánh tím đỏ",
       "Kem nhuộm dưỡng tóc thời trang L'Oreal Paris Excellence Fashion 172ml Nâu Đỏ Ánh Cam",
       "Màu nhuộm dưỡng tóc phủ bạc L'Oreal Paris Excellence Crème 172ml Nâu ánh đỏ",
       "Kem Nhuộm Dưỡng Tóc Phủ Bạc L'Oréal Paris Excellence Crème 172ml - 4.15 Nâu Tro Ánh Đỏ",
       'Dầu xả bảo vệ nhuộm tóc 7 tuần Color Protect',
       'Kem Nền Mịn Nhẹ Kiềm Dầu Chống Nắng Fit Me Dạng Tuýp Maybelline New York Matte Foundation 5ml - Màu 115',
       "Kem nhuộm dưỡng tóc thời trang L'Oreal Paris Excellence Fashion 172ml Nâu Vàng Ánh Khói",
       "Son lì mịn môi L'Oréal Paris Color Riche Matte",
       'Túi bao tử nhiều màu Maybelline New York 1',
       "Kem chống nắng bảo vệ dưỡng da se mịn lỗ chân lông & chống ô nhiễm L'Oreal Paris UV Perfect fresh & Matte SPF50/PA++++ 15ml",
       "Tinh chất tăng cường săn chắc da và giảm nếp nhăn L'Oreal Paris Revitalift Essence 30ml",
       "Nước tẩy trang đa năng 3-in-1 L'Oreal Paris Micellar kiềm dầu cho làn da sáng mịn rạng rỡ 400ml",
       'Kem chống nắng L’Oreal Paris UV Defender 15ml - Nâng tông giảm thâm (Viền hồng)',
       'Son Kem Lì 16H Lâu Trôi Maybelline New York Super Stay Matte Ink Lipstick 2.7ml - 20 Pioneer',
       "Kem nhuộm dưỡng tóc màu thời trang L'Oreal Paris Excellence Fashion 172ml",
       'Son Lì Mịn Môi Siêu Nhẹ Cao Cấp Maybelline New York Color Sensational Ultimatte 1.7g',
       'Kem dưỡng serum sáng da ban ngày Garnier Light Complete Vitamin C Serum Cream SPF30 50ml',
       'Mặt nạ tinh chất Sữa tươi & Vitamin C sáng mượt da Garnier Light Complete White Up Serum Mask 28g',
       'Mặt nạ tinh chất Trà xanh & Hyaluron kiềm dầu Garnier Hydra Bomb Green Tea Serum Mask 28g',
       'Mặt nạ tinh chất Sakura & Hyarulon căng mướt da Garnier Hydra Bomb Sarura White Serum Mask 28g',
       'Tinh chất tăng cường sáng da mờ thâm Garnier Light Complete 30x Vitamin C Booster Serum 30ml',
       'Mặt nạ tinh chất Vitamin C & Salycilic Acid giảm mụn Garnier Bright Complete Anti Acne Serum Mask 23g',
       'Mặt nạ tinh chất Hoa oải hương & Hyarulon thư giãn da Garnier Hydra Bomb Lavender Serum Mask 28g',
       'Mặt nạ tinh chất rong biển & than tre thanh lọc da Garnier Charcoal & Black Algae Serum Mask 28g'],
      dtype=object)

In [21]:
# Ở cột product_category, các giá trị thiếu hoặc sai với tên sản phẩm trong cột product_name
# Cần chuẩn hoá lại cho phù hợp với tên sản phẩm trong cột product_name

# Từ điển phân loại sản phẩm
# Lưu ý: thứ tự quan trọng — keyword cụ thể hơn phải đứng TRƯỚC keyword chung hơn

# map_category: product_name -> {'category': ..., 'sub_category': ...}
# Dua tren taxonomy nganh beauty (cap 1 = category, cap 2 = sub_category)
# Luu y: 'Nuoc tay trang' va 'Phu kien/Qua tang' la gia dinh cua toi, anh goc khong co tag rieng

map_category = {
    'Bút Cushion Che Khuyết Điểm Đa Năng Instant Age Rewind Eraser Multi-use Concealer Maybelline New York 6ml': {'category': 'Makeup', 'sub_category': 'Face'},
    'Bút Kẻ Mày 3 Đầu L\'Oréal Paris Brow Artist Designer Pro 3-IN-1': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Bút Kẻ Mắt Lâu Trôi L\'Oreal Paris Flash Cat Eye By Superliner': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Bút Kẻ Mắt Nước Lâu Trôi 36H không thấm nước Maybelline New York Line Tattoo High Impact Liner 1g': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Bút Kẻ Mắt Nước Siêu Mảnh Không Lem Không Trôi Maybelline New York Hypersharp Liner Đen 0.5g': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Bút kẻ mắt 2 đầu Super Liner Duo Designer': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Bảng Phấn Mắt Maybelline New York 6 Màu Mini Palette 4g': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Bộ Serum Siêu Cấp Ẩm Và Sáng Da L\'ORÉAL PARIS Pure Hyaluronic Acid 1.5%': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Bộ Thuốc Nhuộm Dưỡng Tóc Phủ Bạc Excellence No.3 - Nâu Đen Tự Nhiên': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Bộ thuốc nhuộm dưỡng tóc phủ bạc Excellence No.6.35 - Nâu chocolate': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Chì Kẻ Mày 2 Đầu L\'Oréal Paris Brow Artist Xpert': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Chì Kẻ Mày 2 Đầu Sắc Nét Tự Nhiên Maybelline New York Define & Blend Brow Pencil 0.16g': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Chì Kẻ Mày 2 Đầu Với Đầu Chì Xéo Mềm Mịn 12H Maybelline New York Fashion Brow Cream Pencil 0.8g': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Dưỡng Chất Căng Mướt Da L\'Oreal Paris Crystal Micro Essence 22ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Dưỡng Chất Căng Mướt Da L\'Oréal Paris Revitalift Crystal Micro Essence 130ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Dưỡng Chất Căng Mướt Da L\'Oréal Paris Revitalift Crystal Micro Essence 65ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Dưỡng chất căng mướt da L\'Oreal Paris Crystal Micro Essence 130ml - Phiên bản giới hạn': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Dầu dưỡng chiết xuất tinh dầu hoa tự nhiên L\'Oréal Paris Elseve Extraordinary Oil 100ml': {'category': 'Hair Care', 'sub_category': 'Treatment'},
    'Dầu gội chiết xuất tinh dầu hoa tự nhiên L\'Oreal Paris Elseve Extraordinary Oil 130ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu gội chiết xuất tinh dầu hoa tự nhiên L\'Oréal Paris Elseve Extraordinary Oil 330ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu gội chiết xuất tinh dầu hoa tự nhiên L\'Oréal Paris Elseve Extraordinary Oil 650ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu gội giữ màu tóc nhuộm L\'oreal Paris Elseve Color Protect Protecting Shampoo': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu gội ngăn gãy rụng tóc L\'Oreal Paris Elseve Fall Resist 3X Shampoo 170ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu gội ngăn gãy rụng tóc L\'Oreal Paris Elseve Fall Resist 3X Shampoo 330ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu gội ngăn gãy rụng tóc L\'Oreal Paris Elseve Fall Resist 3X Shampoo 650ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu gội phục hồi tóc L\'oreal Paris Elseve Total Repair 5 Repairing Shampoo 330ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu gội phục hồi tóc L\'oreal Paris Elseve Total Repair 5 Repairing Shampoo 650ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu xả L\'Oréal Paris Elseve Color Protect 7 Weeks Conditioner 325ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu xả Phục Hồi Tóc L\'oreal Paris Elseve Total Repair 5 Repairing Conditioner 325ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu xả bảo vệ nhuộm tóc 7 tuần Color Protect': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu xả chiết xuất tinh dầu hoa tự nhiên L\'Oréal Paris Elseve Extraordinary Oil 325ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu xả ngăn gãy rụng tóc L\'Oreal Paris Elseve Fall Resist 3X Conditioner 165ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Dầu xả ngăn gãy rụng tóc L\'Oreal Paris Elseve Fall Resist 3X Conditioner 325ml': {'category': 'Hair Care', 'sub_category': 'Cleansing'},
    'Hoạt chất tươi trẻ da chống lão hóa L\'Oreal Paris Youth Code Skin Activating Ferment Pre-Essence 30ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem Che Khuyết Điểm L\'Oreal Paris Infallible More Than Concealer': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem Che Khuyết Điểm Mịn Lì Tiệp Mọi Tông Da Fit Me Concealer Maybelline New York 6.8ml': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem Nhuộm Dưỡng Tóc Phủ Bạc L\'Oréal Paris Excellence Crème 172ml - 1 Đen Tự Nhiên': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Kem Nhuộm Dưỡng Tóc Phủ Bạc L\'Oréal Paris Excellence Crème 172ml - 4.15 Nâu Tro Ánh Đỏ': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Kem Nền Mịn Nhẹ Kiềm Dầu Chống Nắng Fit Me Dạng Tuýp Maybelline New York Matte Foundation 5ml - Màu 115': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem Nền Mịn Nhẹ Kiềm Dầu Chống Nắng Fit Me Dạng Tuýp Maybelline New York Matte Foundation 5ml - Màu 120': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem Nền Mịn Nhẹ Kiềm Dầu Fit Me Dạng Tuýp Maybelline New York Matte Foundation 18ml': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem Nền Mịn Nhẹ Kiềm Dầu Fit Me Maybelline New York Matte Poreless Foundation 30ml': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem Nền Siêu Che Phủ Lâu Trôi Maybelline Super Stay Full Coverage Foundation 30ml': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem Trang Điểm Bb Che Khuyết Điểm Và Chống Nắng Maybelline New York Super Bb Ultra Cover SPF 50 PA++++ 30ml': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem che khuyết điểm L\'Oreal Paris True Match The One Concealer 6.8ml': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem chống nắng L\'Oreal Paris UV Perfect trắng sáng tức thì 15ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem chống nắng L’Oreal Paris UV Defender 15ml - Nâng tông giảm thâm (Viền hồng)': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem chống nắng Nâng tông Giảm thâm Mịn Nhẹ Bảo vệ da L’Oreal Paris UV Defender 50ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem chống nắng bảo vệ & dưỡng da se mịn lỗ chân lông & chống ô nhiễm L\'Oreal Paris UV Perfect fresh & Matte SPF50/PA++++ 7ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem chống nắng bảo vệ dưỡng da se mịn lỗ chân lông & chống ô nhiễm L\'Oreal Paris UV Perfect fresh & Matte SPF50/PA++++ 15ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem chống nắng dưỡng trắng da L\'Oréal Paris UV Perfect Rosy White SPF50+/PA ++++': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem chống nắng dưỡng ẩm & chống nhờn rít L\'Oréal Paris UV Perfect Super Aqua Essence SPF50+ PA++++': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem chống nắng kiềm dầu & se mịn lỗ chân lông L\'Oréal Paris UV Perfect Fresh & Matte SPF50+ PA++++': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem chống nắng trang điểm L\'Oréal Paris UV Perfect BB Max SPF50+ PA++++': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem dưỡng L’Oreal Paris White Perfect ban ngày SPF17 PA++ 7ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem dưỡng da trắng sáng L\'Oreal White Perfect Day Cream SPF17 PA++ 50ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem dưỡng da vùng mắt chống lão hóa L\'Oreal Paris Dex Revitalift Eye Cream 15ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem dưỡng serum sáng da ban ngày Garnier Light Complete Vitamin C Serum Cream SPF30 50ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem dưỡng săn chắc da và giảm nếp nhăn ban ngày L\'Oréal Paris Revitalift SPF23 PA++ 50ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem dưỡng săn chắc da và giảm nếp nhăn ban đêm L\'Oréal Paris Revitalift 50ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem dưỡng trắng mịn và giảm thâm nám ban ngày L\'Oréal Paris White Perfect Clinical SPF19/PA+++ 50ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem dưỡng trắng mịn và giảm thâm nám ban đêm L\'Oreal Paris White Perfect Clinical Night Cream 50ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem dưỡng trắng sáng đều màu da L\'Oreal White Perfect Fairness Revealing Soothing Night Cream 50ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Kem lót mịn da che khuyết điểm Maybelline New York Baby Skin Pore Eraser Primer 22ml': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem nhuộm dưỡng tóc màu thời trang L\'Oreal Paris Excellence Fashion 172ml': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Kem nhuộm dưỡng tóc phủ bạc L\'Oréal Paris Excellence Crème 172ml - Nâu tự nhiên': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Kem nhuộm dưỡng tóc phủ bạc L\'Oréal Paris Excellence Crème 172ml - Nâu ánh tím': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Kem nhuộm dưỡng tóc phủ bạc L\'Oréal Paris Excellence Crème 172ml - Nâu ánh tím đỏ': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Kem nhuộm dưỡng tóc phủ bạc L\'Oréal Paris Excellence Crème 172ml - Nâu đen tự nhiên': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Kem nhuộm dưỡng tóc phủ bạc L\'Oréal Paris Excellence Crème 172ml - Nâu đồng ánh đỏ': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Kem nhuộm dưỡng tóc thời trang L\'Oreal Paris Excellence Fashion 172ml Nâu Vàng Ánh Khói': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Kem nhuộm dưỡng tóc thời trang L\'Oreal Paris Excellence Fashion 172ml Nâu Đỏ Ánh Cam': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Kem nền lâu trôi L’Oreal Paris Infallible 24H MATTE COVER': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem nền mịn da dạng lỏng L\'Oréal Paris True Match Liquid Foundation 30ml': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem nền mịn nhẹ lâu trôi L\'Oréal Paris Infallible Fresh Wear 24h 30ml': {'category': 'Makeup', 'sub_category': 'Face'},
    'Kem ủ chiết xuất tinh dầu hoa tự nhiên L\'Oréal Paris Elseve Extraordinary Oil 200ml': {'category': 'Hair Care', 'sub_category': 'Treatment'},
    'Kem ủ ngăn gãy rụng tóc L\'Oreal Paris Elseve Fall Resist 3X 200ml': {'category': 'Hair Care', 'sub_category': 'Treatment'},
    'Kem ủ phục hồi tóc L\'Oréal Paris Total Repair 5 200ml': {'category': 'Hair Care', 'sub_category': 'Treatment'},
    'Kẻ Mắt Nước Maybelline Sắc Nét Không Trôi Màu Đen HyperSharp Power Black Liquid Liner 0.5g': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Mascara Dài Mi & Tơi Mi Tự Nhiên Maybelline New York Lash Sensational Waterproof Chuốt Mi Không Lem Không Trôi 10ml': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Mascara Dài Mi Và Cong Mi Maybelline New York Hyper Curl Waterproof Chuốt Mi Đen Không Lem Không Trôi 9.2ml': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Mascara Dày Mi Cực Đại Maybelline New York The Magnum Big Shot Waterproof Chuốt Mi Không Lem Không Trôi 10ml': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Mascara Dưỡng Mi Collagen Dày Mi Gấp 10 Lần Maybelline New York Colossal Waterproof Chuốt Mi Không Lem Không Trôi 9.2ml': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Mascara L\'Oreal Làm Cong Và Dày Mi Curl Impact Collagene 11ml': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Mascara Uốn Mi, Nâng Mi Và Làm Dày Mi Maybelline New York Falsies Lash Lift 8.6ml': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Mascara làm dày và dài mi L\'Oréal Paris Lash Paradise 7.6ml': {'category': 'Makeup', 'sub_category': 'Eyes'},
    'Màu nhuộm dưỡng tóc phủ bạc L\'Oreal Paris Excellence Crème 172ml': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Màu nhuộm dưỡng tóc phủ bạc L\'Oreal Paris Excellence Crème 172ml Nâu Hạt Dẻ': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Màu nhuộm dưỡng tóc phủ bạc L\'Oreal Paris Excellence Crème 172ml Nâu chocolate': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Màu nhuộm dưỡng tóc phủ bạc L\'Oreal Paris Excellence Crème 172ml Nâu ánh đỏ': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Màu nhuộm dưỡng tóc phủ bạc L\'Oreal Paris Excellence Crème 172ml Vàng Sáng': {'category': 'Hair Care', 'sub_category': 'Color'},
    'Mặt Nạ Giấy Dưỡng Chất Cô Đặc L\'Oréal Paris Revitalift Pro-Youth Face Mask – Dưỡng ẩm da': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Mặt nạ dưỡng chất pha lê Revitalift Crystal Micro-Essence Treatment Mask L\'Oreal Paris 25g': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Mặt nạ giấy dưỡng chất cô đặc L\'Oréal Paris Revitalift Pro-Youth Face Mask - Dưỡng Trắng Da': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Mặt nạ giấy dưỡng chất cô đặc L\'Oréal Paris Revitalift Pro-Youth Face Mask - Săn Chắc Da': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Mặt nạ kết hợp serum căng mịn L\'Oreal Paris Revitalift Fresh Mix Plumping Serum': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Mặt nạ tinh chất Hoa oải hương & Hyarulon thư giãn da Garnier Hydra Bomb Lavender Serum Mask 28g': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Mặt nạ tinh chất Sakura & Hyarulon căng mướt da Garnier Hydra Bomb Sarura White Serum Mask 28g': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Mặt nạ tinh chất Sữa tươi & Vitamin C sáng mượt da Garnier Light Complete White Up Serum Mask 28g': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Mặt nạ tinh chất Trà xanh & Hyaluron kiềm dầu Garnier Hydra Bomb Green Tea Serum Mask 28g': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Mặt nạ tinh chất Vitamin C & Salycilic Acid giảm mụn Garnier Bright Complete Anti Acne Serum Mask 23g': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Mặt nạ tinh chất rong biển & than tre thanh lọc da Garnier Charcoal & Black Algae Serum Mask 28g': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước Tẩy Trang Micellar Dưỡng Da Không Cồn 4 Trong 1 Maybelline New York Micellar Water 4-in-1': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước Tẩy Trang Tươi Mát L\'Oreal Paris 3-in-1 Micellar Water (95ml) tươi mát da': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước Tẩy Trang Tươi Mát L\'Oreal Paris 3-in-1 Micellar Water Sạch Sâu 95ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước Tẩy Trang Tươi Mát L\'Oreal Paris 3-in-1 Micellar Water dưỡng ẩm da 95ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước hoa hồng se khít lỗ chân lông và săn chắc da L\'oreal Paris Revitalift 200ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước hoa hồng se khít lỗ chân lông và trắng mịn da L\'Oréal Paris White Perfect 200ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước tẩy trang L\'Oreal Paris 3-in-1 Micellar Water 400ml: Làm Sạch Trang Điểm': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước tẩy trang mắt và môi L\'Oreal Paris Gentle Care 125ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước tẩy trang đa năng 3-in-1 L\'Oreal Paris Micellar kiềm dầu cho làn da sáng mịn rạng rỡ 400ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước tẩy trang đa năng làm sạch sâu 3-in-1 L\'Oréal Paris Micellar Water 400ml - Dưỡng ẩm da': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Nước tẩy trang đa năng làm sạch sâu 3-in-1 L\'Oréal Paris Micellar Water 400ml - Làm mát da': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Phấn Má Hồng Mịn Nhẹ Tự Nhiên Giữ Màu Chuẩn Fit Me Blush Maybelline New York 4.5g': {'category': 'Makeup', 'sub_category': 'Face'},
    'Phấn Nền Kiềm Dầu Chống Nắng 12H SPF28 PA+++ Mịn Lì Lâu Trôi Fit Me Maybelline New York Compact Powder 6g': {'category': 'Makeup', 'sub_category': 'Face'},
    'Phấn Nền Kiềm Dầu Chống Nắng Tiệp Mọi Tông Da SPF 32 PA+++ Fit Me Skin-Fit Powder Foundation Maybelline New York 9g': {'category': 'Makeup', 'sub_category': 'Face'},
    'Phấn Phủ Kiềm Dầu Siêu Mịn 24h Chống Nắng SPF 32 PA+++ Clear Smooth All In One Maybelline New York Powder Foundation 9g': {'category': 'Makeup', 'sub_category': 'Face'},
    'Phấn Phủ Mịn Da Chống Nhờn Maybelline Clear Smooth All In One Powder 9g': {'category': 'Makeup', 'sub_category': 'Face'},
    'Phấn Phủ Mịn Nhẹ Kiềm Dầu Fit Me Matte Poreless Powder Maybelline New York 8.5g': {'category': 'Makeup', 'sub_category': 'Face'},
    'Phấn nền mịn da L\'Oreal Paris True Match 8g': {'category': 'Makeup', 'sub_category': 'Face'},
    'Serum Siêu cấp ẩm sáng da L\'Oreal Paris Pure Hyaluronic Acid 1.5% 30ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Serum siêu cấp ẩm sáng da 7.5ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Son Bút Chì Mịn Lì 8h Lâu Trôi Maybelline New York Super Stay Ink Crayon Lipstick 1.2g': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Son Dưỡng Môi Baby Lips Bloom Maybelline New York Chống Nắng SPF 16 (Có Màu) 1.7g': {'category': 'Skincare', 'sub_category': 'Lip Care'},
    'Son Kem Lì 16H Lâu Trôi Maybelline New York Super Stay Matte Ink Lipstick 2.7ml - 20 Pioneer': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Son Kem Lì 16h Lâu Trôi Maybelline New York Super Stay Matte Ink Lipstick 5ml': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Son Kem Lì Nhẹ Môi Maybelline New York Sensational Liquid Matte Lipstick 7ml': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Son Kem Lì Nhẹ Môi Phiên Bản Tông Đất Maybelline New York Sensational Liquid Matte The Nudes Lipstick 7ml': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Son Lì Mịn Môi Maybelline New York': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Son Lì Mịn Môi Siêu Nhẹ Cao Cấp Maybelline New York Color Sensational Ultimatte 1.7g': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Son Thỏi  lì Mịn Môi L\'Oréal Paris Color Riche Matte 3.7g': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Son lì mịn môi L\'Oréal Paris Color Riche Matte': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Son satin mịn mượt cao cấp L\'Oreal Paris Color Riche Satin 3.7g': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Son tint mịn lì cao cấp L\'Oréal Paris Rouge Signature 7ml': {'category': 'Makeup', 'sub_category': 'Lips'},
    'Sữa rửa mặt dưỡng trắng và sáng mịn da L\'Oréal Paris White Perfect 100ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Sữa rửa mặt dưỡng trắng và sáng mịn da L\'Oréal Paris White Perfect 50ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Sữa rửa mặt săn chắc da L\'Oreal Revitalift Milky Cleansing Foam 100ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Sữa tẩy trang L\'Oreal Paris Dermo Expertise Gentle Cleansing Milk 200ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Tinh chất tăng cường dưỡng da trắng mịn & giảm thâm nám L\'Oréal Paris White Perfect Clinical 30ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Tinh chất tăng cường sáng da mờ thâm Garnier Light Complete 30x Vitamin C Booster Serum 30ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'Tinh chất tăng cường săn chắc da và giảm nếp nhăn L\'Oreal Paris Revitalift Essence 30ml': {'category': 'Skincare', 'sub_category': 'Face Care'},
    'TÚI LƯỚI DU LỊCH TIỆN DỤNG_MÀU TRẮNG': {'category': 'Khác', 'sub_category': 'Khác'},
    'Túi bao tử nhiều màu Maybelline New York 1': {'category': 'Khác', 'sub_category': 'Khác'},
    'Túi metallic Da Pha Lê L\'Oreal Paris': {'category': 'Khác', 'sub_category': 'Khác'},
    'Túi tote L\'Oréal Paris I\'M WORTH IT': {'category': 'Khác', 'sub_category': 'Khác'},
    'Tẩy Trang Mắt Môi Chuyên Dụng Maybelline New York Eye & Lip Makeup Remover': {'category': 'Skincare', 'sub_category': 'Face Care'},
}

def normalize_product_name(name):
    return re.sub(r'\s+', ' ', str(name)).strip().lower()

product_taxonomy_map = {
    normalize_product_name(product_name): taxonomy
    for product_name, taxonomy in map_category.items()
}

def map_product_taxonomy(name):
    return product_taxonomy_map.get(
        normalize_product_name(name),
        {'category': 'Khác', 'sub_category': 'Khác'}
    )

taxonomy_df = df['product_name'].apply(map_product_taxonomy).apply(pd.Series)
taxonomy_df = taxonomy_df.rename(columns={'category': 'product_category'})

df[['product_category', 'sub_category']] = taxonomy_df[['product_category', 'sub_category']]

df[['product_name', 'product_category', 'sub_category']].head()

,product_name,product_category,sub_category
1,Kem Nền Siêu Che Phủ Lâu Trôi Maybelline Super...,Makeup,Face
3,Kem chống nắng L'Oreal Paris UV Perfect trắng ...,Skincare,Face Care
4,Kem dưỡng L’Oreal Paris White Perfect ban ngày...,Skincare,Face Care
5,Kem chống nắng Nâng tông Giảm thâm Mịn Nhẹ Bảo...,Khác,Khác
6,Serum siêu cấp ẩm sáng da 7.5ml,Skincare,Face Care