In [1]:
import os
import pandas as pd
import datetime as dt
from urllib.parse import urlparse
import re
import numpy as np

### Part 1: Combine multiple tables into a single table

In [ ]:
path = "D:/Data Self Learning/Tran Hoang Long _ Data Analyst Course/Data Analyst/Market basket Association/Raw Data/"
frames = []
for file in os.listdir(path):
    if file.endswith(".xlsx"):
        filepath = os.path.join(path, file)
        df_tmp = pd.read_excel(filepath)
        frames.append(df_tmp)
df = pd.concat(frames, ignore_index=True)

In [3]:
df.head(10)

,Nhà sản xuất,Khách hàng,Email khách hàng,Năm,Tháng,Ngày,Nguồn lưu lượng (Traffic),Tham số,Nguồn giới thiệu (Referral),UTM_campaign,...,T.trạng đ.hàng,Phương thức thanh toán,Số đơn hàng,Doanh thu,Tiền khuyến mãi,Doanh thu thuần,Tổng hóa đơn,Đã thu,Số lượng,Vận chuyển
0,--,Hoàng khánh ngọc,khanhngoc20077@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,0,0.0,0.0,30000.0,0.0,0,30000
1,Maybelline New York,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,Direct,--,--,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,199000,0.0,199000.0,199000.0,0.0,1,0
2,--,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,Direct,--,--,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,0,0.0,0.0,30000.0,0.0,0,30000
3,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,210005,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,1,-1.0,0.0,0.0,0.0,1,0
4,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,210005,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,2,-2.0,0.0,0.0,0.0,2,0
5,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,199000,-20000.0,179000.0,179000.0,0.0,1,0
6,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,1,0.0,1.0,1.0,0.0,1,0
7,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,109000,0.0,109000.0,109000.0,0.0,1,0
8,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,169000,0.0,169000.0,169000.0,0.0,1,0
9,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,169000,0.0,169000.0,169000.0,0.0,1,0

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28449 entries, 0 to 125
Data columns (total 36 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Nhà sản xuất                 28449 non-null  object
 1   Khách hàng                   28449 non-null  object
 2   Email khách hàng             28449 non-null  object
 3   Năm                          28449 non-null  datetime64[ns]
 4   Tháng                        28449 non-null  datetime64[ns]
 5   Ngày                         28449 non-null  datetime64[ns]
 6   Nguồn lưu lượng (Traffic)    28449 non-null  object
 7   Tham số                      28206 non-null  object
 8   Nguồn giới thiệu (Referral)  28449 non-null  object
 9   UTM_campaign                 28449 non-null  object
 10  UTM_content                  28449 non-null  object
 11  UTM_medium                   28449 non-null  object
 12  UTM_source                   28449 non-null  object
 13  UTM_term                     28449 non-null  object
 14  Chi nhánh                    28449 non-null  object
 15  Nhân viên tạo                28449 non-null  object
 16  Loại sản phẩm                28449 non-null  object
 17  Tỉnh thành                   28449 non-null  object
 18  Trang                        28449 non-null  object
 19  Kênh bán hàng                28449 non-null  object
 20  Đơn hàng                     28449 non-null  int64
 21  Sản phẩm                     28449 non-null  object
 22  SKU                          28449 non-null  object
 23  Quận huyện vận chuyển        28449 non-null  object
 24  Phiên bản                    28449 non-null  object
 25  T.trạng t.toán               28449 non-null  object
 26  T.trạng đ.hàng               28449 non-null  object
 27  Phương thức thanh toán       28449 non-null  object
 28  Số đơn hàng                  28449 non-null  int64
 29  Doanh thu                    28449 non-null  int64
 30  Tiền khuyến mãi              28449 non-null  float64
 31  Doanh thu thuần              28449 non-null  float64
 32  Tổng hóa đơn                 28449 non-null  float64
 33  Đã thu                       28449 non-null  float64
 34  Số lượng                     28449 non-null  int64
 35  Vận chuyển                   28449 non-null  int64
dtypes: datetime64[ns](3), float64(4), int64(5), object(24)
memory usage: 8.0+ MB

##### 1. Change table column name from vietnamese to english

In [5]:
rename_columns = {
    "Nhà sản xuất": "manufacturer",
    "Khách hàng": "customer",
    "Email khách hàng": "customer_email",
    "Năm": "year",
    "Tháng": "month",
    "Ngày": "date",
    "Nguồn lưu lượng (Traffic)": "traffic_source",
    "Tham số": "parameter",
    "Nguồn giới thiệu (Referral)": "referral",
    "UTM_campaign": "utm_campaign",
    "UTM_content": "utm_content",
    "UTM_medium": "utm_medium",
    "UTM_source": "utm_source",
    "UTM_term": "utm_term",
    "Chi nhánh": "branch",
    "Nhân viên tạo": "created_by",
    "Loại sản phẩm": "product_category",
    "Tỉnh thành": "province",
    "Trang": "page",
    "Kênh bán hàng": "sale_channel",
    "Đơn hàng": "order_id",
    "Sản phẩm": "product_name",
    "SKU": "sku",
    "Quận huyện vận chuyển": "district",
    "Phiên bản": "version",
    "T.trạng t.toán": "payment_status",
    "T.trạng đ.hàng": "order_status",
    "Phương thức thanh toán": "payment_method",
    "Số đơn hàng": "order_count",
    "Doanh thu": "revenue",
    "Tiền khuyến mãi": "discount_amount",
    "Doanh thu thuần": "net_revenue",
    "Tổng hóa đơn": "total_invoice",
    "Đã thu": "amount_received",
    "Số lượng": "quantity",
    "Vận chuyển": "shipping_fee"
}

df.rename(columns=rename_columns, inplace=True)

In [6]:
df.head(10)

,manufacturer,customer,customer_email,year,month,date,traffic_source,parameter,referral,utm_campaign,...,order_status,payment_method,order_count,revenue,discount_amount,net_revenue,total_invoice,amount_received,quantity,shipping_fee
0,--,Hoàng khánh ngọc,khanhngoc20077@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,0,0.0,0.0,30000.0,0.0,0,30000
1,Maybelline New York,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,Direct,--,--,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,199000,0.0,199000.0,199000.0,0.0,1,0
2,--,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,Direct,--,--,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,0,0.0,0.0,30000.0,0.0,0,30000
3,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,210005,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,1,-1.0,0.0,0.0,0.0,1,0
4,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,210005,http://m.facebook.com,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,2,-2.0,0.0,0.0,0.0,2,0
5,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,199000,-20000.0,179000.0,179000.0,0.0,1,0
6,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,1,0.0,1.0,1.0,0.0,1,0
7,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,109000,0.0,109000.0,109000.0,0.0,1,0
8,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,169000,0.0,169000.0,169000.0,0.0,1,0
9,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-01-01,2021-05-01,2021-05-26,fb,--,https://shop.lorealparis.com.vn//?ref=210007&u...,--,...,Không hủy,Thanh toán khi giao hàng (COD),1,169000,0.0,169000.0,169000.0,0.0,1,0

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 28449 entries, 0 to 125
Data columns (total 36 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   manufacturer      28449 non-null  object
 1   customer          28449 non-null  object
 2   customer_email    28449 non-null  object
 3   year              28449 non-null  datetime64[ns]
 4   month             28449 non-null  datetime64[ns]
 5   date              28449 non-null  datetime64[ns]
 6   traffic_source    28449 non-null  object
 7   parameter         28206 non-null  object
 8   referral          28449 non-null  object
 9   utm_campaign      28449 non-null  object
 10  utm_content       28449 non-null  object
 11  utm_medium        28449 non-null  object
 12  utm_source        28449 non-null  object
 13  utm_term          28449 non-null  object
 14  branch            28449 non-null  object
 15  created_by        28449 non-null  object
 16  product_category  28449 non-null  object
 17  province          28449 non-null  object
 18  page              28449 non-null  object
 19  sale_channel      28449 non-null  object
 20  order_id          28449 non-null  int64
 21  product_name      28449 non-null  object
 22  sku               28449 non-null  object
 23  district          28449 non-null  object
 24  version           28449 non-null  object
 25  payment_status    28449 non-null  object
 26  order_status      28449 non-null  object
 27  payment_method    28449 non-null  object
 28  order_count       28449 non-null  int64
 29  revenue           28449 non-null  int64
 30  discount_amount   28449 non-null  float64
 31  net_revenue       28449 non-null  float64
 32  total_invoice     28449 non-null  float64
 33  amount_received   28449 non-null  float64
 34  quantity          28449 non-null  int64
 35  shipping_fee      28449 non-null  int64
dtypes: datetime64[ns](3), float64(4), int64(5), object(24)
memory usage: 8.0+ MB

##### 2. Drop some unnecessary columns for transaction data

In [8]:
# các cột year, month ở dạng datetime chỉ chứa dữ liệu về năm, tháng nên trở nên dư thừa
# các cột như parameter, utm_campaign, utm_content, utm_medium, utm_source, utm_term, created_by, page, sale_chanel, sku không có đầy dủ thông tin hoặc không có tác dụng cho mục đích xây báo cáo sau này
# cột payment_status không có tác dụng bởi vì đây là dữ liệu từ năm 2021

df.drop(['year', 'month', 'parameter', 'utm_campaign', 'utm_content', 'utm_medium', 'utm_source', 'utm_term', 'created_by', 'page', 'sale_channel', 'sku', 'payment_status', 'order_count', 'net_revenue'], axis= 1, inplace= True)

### Part 2: Data Cleaning

In [9]:
# Dữ liệu nguồn chứa các bản ghi về shipping, quà tặng, giao dịch của từng món hàng trong hoá đơn
# Cần tách ra để dễ xử lý dữ liệu và phù hợp cho việc Data Modeling sau này

shipping_df = df[df['product_name'] == '--'][['order_id', 'shipping_fee']]

df_gift = df[
    df['product_name'].str.contains(r'\[(quà tặng|gift|Quà tặng không bán)\]', case=False, na=False)
][['order_id', 'product_name']]

# Xoá cả dòng shipping và dòng quà tặng
df = df[
    (df['product_name'] != '--') & 
    (~df['product_name'].str.contains(r'\[(quà tặng|gift|Quà tặng không bán)\]', case=False, na=False))
]

# Xoá các ký tự không cần thiết trong tên quà tặng
df_gift = df_gift.rename(columns={'product_name': 'gift_name'})

df_gift['gift_name'] = df_gift['gift_name'].str.replace(
    r'\[(quà tặng|gift|Quà tặng không bán)\]', 
    '', 
    case=False,  # không phân biệt hoa thường
    regex=True
).str.strip()

# Chỉnh sửa kiểu dữ liệu cho cột date
df['date'] = df['date'].dt.date

C:\Users\dangv\AppData\Local\Temp\ipykernel_87984\2725251162.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df['product_name'].str.contains(r'\[(quà tặng|gift|Quà tặng không bán)\]', case=False, na=False)
C:\Users\dangv\AppData\Local\Temp\ipykernel_87984\2725251162.py:13: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  (~df['product_name'].str.contains(r'\[(quà tặng|gift|Quà tặng không bán)\]', case=False, na=False))

In [10]:
# Một số dữ liệu ở cột referral quá dài không phù hợp để dưa vào mysql
# Cần chuẩn hoá lại dữ liệu của cột mà vẫn giữ nguyên khả năng đưa ra insight

def extract_base_url(url):
    try:
        parsed = urlparse(str(url))
        return f"{parsed.scheme}://{parsed.netloc}/" if parsed.netloc else None
    except:
        return None

df['clean_referral'] = df['referral'].apply(extract_base_url)

In [11]:
df[['referral', 'clean_referral']].drop_duplicates().head(10)

,referral,clean_referral
1,--,None
3,http://m.facebook.com,http://m.facebook.com/
5,https://shop.lorealparis.com.vn//?ref=210007&u...,https://shop.lorealparis.com.vn/
10,https://www.google.com/,https://www.google.com/
24,https://www.youtube.com/,https://www.youtube.com/
33,https://l.facebook.com/,https://l.facebook.com/
68,http://m.facebook.com/,http://m.facebook.com/
273,https://m.kenh14.vn/5-kem-chong-nang-hack-da-d...,https://m.kenh14.vn/
414,https://shop.maybelline.vn/collections/son-kem...,https://shop.maybelline.vn/
578,https://shop.maybelline.vn//?ref=210007&utm_so...,https://shop.maybelline.vn/

In [ ]:
df['referral'] = df['clean_referral']
df.drop(['clean_referral'], axis=1, inplace=True)

In [13]:
df['referral'].value_counts()

http://m.facebook.com/                   2524
https://shop.lorealparis.com.vn/         1921
https://www.goshopback.vn/               1879
https://l.facebook.com/                  1244
https://click.accesstrade.vn/            1051
https://shop.maybelline.vn/               655
https://www.google.com/                   638
https://www.lorealparis.com.vn/           482
https://l.instagram.com/                  293
https://instabio.cc/                       94
https://www.instagram.com/                 70
https://www.youtube.com/                   66
android-app://org.telegram.messenger/      40
https://m.facebook.com/                    33
http://linksanpham.clix9.com/              30
https://www.google.com.vn/                 29
https://fanlnk.to/                         18
https://vinid.net/                         16
https://pub.accesstrade.vn/                16
https://m.kenh14.vn/                       14
android-app://com.google.android.gm/       10
https://www.maybelline.vn/                  8
android-app://m.facebook.com/               8
https://lm.facebook.com/                    6
https://app.harasocial.com/                 4
https://l.messenger.com/                    3
https://kenh14.vn/                          3
https://coccoc.com/                         2
https://pub2.accesstrade.vn/                2
https://www.ecosia.org/                     1
http://app.kenh14.vn/                       1
Name: referral, dtype: int64

In [ ]:
# Trích xuất tên kênh từ các url ở trên

# Danh sách từ khóa & kênh tương ứng
channel_map = {
    'facebook': 'facebook',
    'instagram': 'instagram',
    'youtube': 'youtube',
    'google': 'google',
    'kenh14': 'kenh14',
    'maybelline': 'maybelline',
    'lorealparis': 'lorealparis',
    'harasocial': 'harasocial',
    'accesstrade': 'accesstrade',
    'shopback': 'goshopback',
    'coccoc': 'coccoc',
    'telegram': 'telegram',
    'messenger': 'messenger',
    'vinid': 'vinid',
    'fanlnk': 'fanlnk',        # URL thực tế là fanlnk.to (không phải fanlink.to)
    'instabio': 'instabio',
    'linksanpham': 'linksanpham',
    'ecosia': 'ecosia'
}

def match_channel(url):
    if pd.isna(url):
        return 'none'
    url = str(url).lower()
    for keyword, channel in channel_map.items():
        if keyword in url:
            return channel
    return 'other'


df['Channel'] = df['referral'].apply(match_channel)

In [15]:
df['Channel'].value_counts()

none           11899
facebook        3815
lorealparis     2403
goshopback      1879
accesstrade     1069
google           677
maybelline       663
instagram        363
instabio          94
youtube           66
telegram          40
linksanpham       30
kenh14            18
other             18
vinid             16
harasocial         4
messenger          3
coccoc             2
ecosia             1
Name: Channel, dtype: int64

In [16]:
df['traffic_source'].value_counts()

Direct           11865
Referral          6206
fb                4641
Social             346
Search Engine        2
Name: traffic_source, dtype: int64

In [ ]:
# Xử lý các cột liên quan đến traffice và url để phù hợp với việc phân tích

channel_to_source = {
    "none": "Direct",
    "facebook": "Facebook",
    "lorealparis": "Affiliate",
    "goshopback": "Affiliate",
    "accesstrade": "Affiliate",
    "google": "Search Engine",
    "maybelline": "Affiliate",
    "instagram": "Social",
    "instabio": "Social",
    "youtube": "Social",
    "telegram": "Social",
    "linksanpham": "Affiliate",
    "kenh14": "Affiliate",
    "other": "Affiliate",
    "vinid": "Affiliate",
    "harasocial": "Affiliate",
    "messenger": "Social",
    "coccoc": "Search Engine",
    "ecosia": "Search Engine",
    "fanlnk": "Affiliate"      # fanlnk.to là affiliate link
}

traffic_source_mapping = {
    "Direct": "Direct",
    "fb": "Facebook",
    "Referral": "Affiliate",
    "Social": "Social",
    "Search Engine": "Search Engine"
}

# Hàm xử lý logic chuyển đổi
def determine_final_source(row):
    ts = row['traffic_source']
    ch = row['Channel']
    
    if ts in traffic_source_mapping:
        return traffic_source_mapping[ts]
    elif ch in channel_to_source:
        return channel_to_source[ch]
    else:
        return "Affiliate"

# Tạo cột mới
df['traffic_source'] = df.apply(determine_final_source, axis=1)
df['traffic_source'].value_counts()
# Xoá cột referral và traffic_source cũ
df.drop(['referral', 'Channel'], axis= 1, inplace= True)

In [ ]:
# Ở cột customer_email, một số bản ghi có chứa email test từ hệ thống. VD: test@test.com
# Dùng regex chính xác hơn để tránh filter nhầm email hợp lệ như attest@gmail.com

df = df[~df['customer_email'].str.contains(r'(^test|@test\.)', regex=True, case=False, na=False)]

In [19]:
df.head(10)

,manufacturer,customer,customer_email,date,traffic_source,branch,product_category,province,order_id,product_name,district,version,order_status,payment_method,revenue,discount_amount,total_invoice,amount_received,quantity,shipping_fee
1,Maybelline New York,982285478,thuyan91096@gmail.com,2021-05-26,Direct,Kho Miền Bắc - MBL,Face,Cần Thơ,112403,Kem Nền Siêu Che Phủ Lâu Trôi Maybelline Super...,Quận Ninh Kiều,112 Natural Ivory,Không hủy,Thanh toán khi giao hàng (COD),199000,0.0,199000.0,0.0,1,0
3,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-05-26,Facebook,Kho Miền Nam - OAP,Khác,Hồ Chí Minh,112402,Kem chống nắng L'Oreal Paris UV Perfect trắng ...,Quận 1,Default Title,Không hủy,Thanh toán khi giao hàng (COD),1,-1.0,0.0,0.0,1,0
4,L'Oréal Paris,Ms Tú,tultn05@gmail.com,2021-05-26,Facebook,Kho Miền Nam - OAP,Khác,Hồ Chí Minh,112402,Kem dưỡng L’Oreal Paris White Perfect ban ngày...,Quận 1,7ml,Không hủy,Thanh toán khi giao hàng (COD),2,-2.0,0.0,0.0,2,0
5,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-05-26,Facebook,Kho Miền Bắc - OAP,Khác,Thanh Hóa,112400,Kem chống nắng Nâng tông Giảm thâm Mịn Nhẹ Bảo...,Huyện Vĩnh Lộc,Kiềm dầu thoáng mịn (Viền Xanh lá),Không hủy,Thanh toán khi giao hàng (COD),199000,-20000.0,179000.0,0.0,1,0
6,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-05-26,Facebook,Kho Miền Bắc - OAP,Khác,Lai Châu,112399,Serum siêu cấp ẩm sáng da 7.5ml,Huyện Phong Thổ,Default Title,Không hủy,Thanh toán khi giao hàng (COD),1,0.0,1.0,0.0,1,0
7,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-05-26,Facebook,Kho Miền Bắc - OAP,Khác,Lai Châu,112399,Nước hoa hồng se khít lỗ chân lông và trắng mị...,Huyện Phong Thổ,200ml,Không hủy,Thanh toán khi giao hàng (COD),109000,0.0,109000.0,0.0,1,0
8,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-05-26,Facebook,Kho Miền Bắc - OAP,Dưỡng Chất,Lai Châu,112399,Kem dưỡng trắng sáng đều màu da L'Oreal White ...,Huyện Phong Thổ,50ml,Không hủy,Thanh toán khi giao hàng (COD),169000,0.0,169000.0,0.0,1,0
9,L'Oréal Paris,982285478,thuyan91096@gmail.com,2021-05-26,Facebook,Kho Miền Bắc - OAP,Dưỡng Chất,Lai Châu,112399,Kem dưỡng da trắng sáng L'Oreal White Perfect ...,Huyện Phong Thổ,50ml,Không hủy,Thanh toán khi giao hàng (COD),169000,0.0,169000.0,0.0,1,0
10,L'Oréal Paris,THÚY DIỄM TRẦN THỦY,hung.huynh@loreal.com,2021-05-26,Affiliate,Kho Miền Nam - OAP,Khác,Tây Ninh,112398,Kem chống nắng L'Oreal Paris UV Perfect trắng ...,Huyện Bến Cầu,Default Title,Không hủy,Thanh toán khi giao hàng (COD),4,0.0,4.0,0.0,4,0
11,L'Oréal Paris,THÚY DIỄM TRẦN THỦY,hung.huynh@loreal.com,2021-05-26,Affiliate,Kho Miền Nam - OAP,Sữa Rửa Mặt,Tây Ninh,112398,Sữa rửa mặt dưỡng trắng và sáng mịn da L'Oréal...,Huyện Bến Cầu,Default Title,Không hủy,Thanh toán khi giao hàng (COD),84000,0.0,84000.0,0.0,1,0

In [ ]:
# Ở cột product_category, các giá trị thiếu hoặc sai với tên sản phẩm trong cột product_name
# Cần chuẩn hoá lại cho phù hợp với tên sản phẩm trong cột product_name

# Từ điển phân loại sản phẩm
# Lưu ý: thứ tự quan trọng — keyword cụ thể hơn phải đứng TRƯỚC keyword chung hơn
category_map = {
    'serum': 'Dưỡng Chất',
    'tinh chất': 'Dưỡng Chất',
    'dưỡng chất': 'Dưỡng Chất',
    'hoạt chất': 'Dưỡng Chất',       # VD: Hoạt chất tươi trẻ da (Pre-Essence)
    'toner': 'Dưỡng Chất',
    'nước hoa hồng': 'Dưỡng Chất',   # Phải đứng TRƯỚC 'nước hoa' để tránh match sai
    'kem chống nắng': 'Face',
    'kem dưỡng': 'Dưỡng Chất',
    'nước hoa': 'Khác',               # Nước hoa (perfume) - đứng SAU 'nước hoa hồng'
    'sữa rửa mặt': 'Sữa Rửa Mặt',
    'tẩy trang': 'Tẩy Trang',
    'kem nền': 'Kem Nền',
    'kem lót': 'Kem Nền',
    'che khuyết điểm': 'Face',
    'bút che khuyết điểm': 'Face',
    'cushion': 'Kem Nền',
    'phấn nền': 'Face',
    'phấn phủ': 'Face',
    'phấn mắt': 'Eyes',               # VD: Bảng Phấn Mắt (eyeshadow palette)
    'má hồng': 'Face',                # VD: Phấn Má Hồng (blush)
    'son lì': 'Lips',
    'son kem': 'Son kem',
    'son': 'Lips',
    'chì kẻ': 'Chì Kẻ Mày',
    'kẻ mày': 'Chì Kẻ Mày',
    'kẻ mắt': 'Eyes',
    'mascara': 'Eyes',
    'dưỡng mi': 'Eyes',
    'dưỡng tóc': 'Khác',
    'màu nhuộm': 'Khác',
    'túi': 'Khác',
    'combo': 'Khác',
    'gel rửa mặt': 'Cleansing',
    'mặt nạ': 'Cleansing',
}

def map_to_final_category(name):
    name_lower = str(name).lower()
    for keyword, category in category_map.items():
        if keyword in name_lower:
            return category
    return 'Khác'

df['product_category'] = df['product_name'].apply(map_to_final_category)

In [ ]:
# Xuất ra file csv sau khi đã xử lý dữ liệu

base_output = "D:/Data Self Learning/Tran Hoang Long _ Data Analyst Course/Data Analyst/Market basket Association/Cleaned_Data/"

df.to_csv(base_output + 'Transaction_Data.csv', encoding='utf-8-sig', index=False)
df_gift.to_csv(base_output + 'Gift_Data.csv', encoding='utf-8-sig', index=False)
shipping_df.to_csv(base_output + 'Shipping_Data.csv', encoding='utf-8-sig', index=False)

print(f"Transaction_Data: {len(df)} rows")
print(f"Gift_Data:        {len(df_gift)} rows")
print(f"Shipping_Data:    {len(shipping_df)} rows")